### PR TITLE
Fix android keyboards

### PR DESCRIPTION
**Pull request by RaulPROP**
This PR tries to solve the issues discussed at #194 .

It does so by updating this package to the equivalent at slate-react@0.82.1 (mainly the commits from [this PR](https://github.com/ianstormtaylor/slate/pull/4988)).

There are still some issues to tackle:

1. When selecting something using android and GBoard (w/ english layout), when typing the characters (most of the times, not always), appears before the cursor. The desired outcome would be that the characters always come after the cursor.
2. The test: `Editable Component > should use default logic to show placeholder when set placeholder value` fails.

### CODE REVIEW

**Comment by pubuzhixing8** [comment]
@RaulPROP Thanks for your contribution, I think we can try to solve this together.

**Comment by RaulPROP** [comment]
Another mayor bug:
- (using android and english GBoard) If you click `enter` in the middle of a paragraph, the text after the cursor gets duplicated (and something weird happens with the `data-slate-key`.

e.g.:
```
This is the part before the cursor|  this is the part after the cursor [data-slate-key=1]
```
(enter)
```
This is the part before the cursor [data-slate-key=2]
this is the part after the cursor [data-slate-key=3]
this is the part after the cursor [data-slate-key=1]
```

**Comment by pubuzhixing8** [comment]
@RaulPROP Can you submit a PR with only the necessary changes? Now contains too many formatting modifications, not good for communication

**Comment by RaulPROP** [comment]
@pubuzhixing8 Thanks for your time.

The problem is that I used the `prettier --write` command (also used in the husky callback) to lint everything instead of just the commited files. I think that after this PR, you should declare a `.prettierrc` [configuration file](https://prettier.io/ sodocs/en/configuration.html) so anyone easily lint a file without bluring the PR (depending on the IDE, when you open a file it lints it based on the linter rules).

I will try to undo the linting changes now.

**Comment by RaulPROP** [comment]
Closed in favor of #212 (same changes without the linting)

**Comment by pubuzhixing8** [comment]
> @pubuzhixing8 Thanks for your time.
> 
> The problem is that I used the `prettier --write` command (also used in the husky callback) to lint everything instead of just the commited files. I think that after this PR, you should declare a `.prettierrc` [configuration file](https://prettier.io/docs/en/configuration.html) so anyone easily lint a file without bluring the PR (depending on the IDE, when you open a file it lints it based on the linter rules).
> 
> I will try to undo the linting changes now.

Received

**Pull request closed without merging**
